// Generated by CoffeeScript 1.4.0
var nodify, shopify;

shopify = require('wlaurance-nodify-shopify');

nodify = shopify.createSession(process.env.SHOP_NAME, process.env.SHOP_PERSISTENT_TOKEN);

exports.listProductImages = function(cb) {
  return nodify.product.all({}, function(error, products) {
    var entity, images, img, _i, _j, _len, _len1, _ref;
    images = [];
    for (_i = 0, _len = products.length; _i < _len; _i++) {
      entity = products[_i];
      if (entity.images) {
        _ref = entity.images;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          img = _ref[_j];
          images.push(img.src);
        }
      }
    }
    return cb(images);
  });
};
