// Generated by CoffeeScript 1.4.0
var app, assets, express, port, shopify, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

shopify = require(__dirname + '/api/shopify-wrapper');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return shopify.listProductImages(function(images) {
    return resp.render('index', {
      images: images
    });
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
